name: nginx
formatter:
  flat:
    timestamp_format: "%Y-%m-%d %H:%M:%S"
    template: '{{timestamp}} <{{level | upper | align_left(width=5)}}> {{logger}} {{file}}/{{line}} {{method}} - {{message}}'
  #json:
  #  style: bunyan
num_of_lines: 10
timestamp:
  begin: 2014-11-28T21:00:09+08:00
  end: 2014-11-28T22:00:09+08:00
host:
- app1
- app2
- app3
- lb1
- lb2
logger:
- name: req
  message:
  - template: request begin
    file: req_handler.c
    line: 11
    method: main
    level: info
  - template: request end
    file: req_handler.c
    line: 71
    method: main
    level: warn
- name: resp
  message:
  - template: response begin
    file: resp_handler.c
    line: 18
    method: main
    level: error
  - template: response end
    file: resp_handler.c
    line: 88
    method: main
    level: debug
- name: session
  message:
  - template: session created
    file: session_handler.c
    line: 25
    method: main
    level: trace
