version: '2.2'

services:

  mysql:
    container_name: bts.mysql
    extends:
      file:   ./docker-compose.base.yml
      service: mysql

  app:
    container_name: bts.app
    extends:
      file:   ./docker-compose.base.yml
      service: app
    environment:
      - MYSQL_URL=jdbc:mysql://mysql:3306/bts?useSSL=false&connectTimeout=300000&socketTimeout=300000
      - FLYWAY_URL=jdbc:mysql://mysql:3306/bts?useSSL=false&connectTimeout=300000&socketTimeout=300000
    depends_on:
      mysql:
        condition: service_healthy


